import type { z } from "zod";

/**
 * On-device minting (E1.2). Primary keys are never auto-generated by the
 * store — `lib/db/schema.ts` pins every insert type to the full entity — so
 * the repo layer is where ids and creation timestamps come from. Keeping it
 * in one place means no bead has to remember the branded-id or the
 * millisecond-ISO convention.
 */

/** A fresh branded id: UUID by convention (PLAN §8, `lib/types/ids.ts`). */
export function mintId<S extends z.ZodType>(schema: S): z.output<S> {
  return schema.parse(crypto.randomUUID());
}

/**
 * Now, in the exact `toISOString()` form `isoTimestampSchema` enforces —
 * millisecond precision is what makes stored timestamps sort chronologically
 * as IndexedDB strings (duel replay E4.2, staleness ranges E5.1).
 */
export function nowIso(): string {
  return new Date().toISOString();
}
